# Generated by Django 3.0.dev20190531161155 on 2019-06-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_class', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('birthday', models.DateField(null=True)),
                ('e_mail', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('identify_code', models.CharField(max_length=20, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user_class',
                 models.ForeignKey(default='普通用户', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='Main.UserClass')),
            ],
        ),
    ]
