# Generated by Django 3.0.dev20190531161155 on 2019-06-11 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50, null=True)),
                ('translator', models.CharField(max_length=50, null=True)),
                ('ISBN', models.CharField(max_length=20, null=True)),
                ('edition', models.CharField(max_length=10, null=True)),
                ('publication_date', models.CharField(max_length=6, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NounProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun_property_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_class_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('birthday', models.DateField(null=True)),
                ('e_mail', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('identify_code', models.CharField(max_length=20, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user_class',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.UserClass')),
            ],
        ),
        migrations.CreateModel(
            name='ProperNounIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=20)),
                ('Noun', models.CharField(max_length=30)),
                ('page', models.CharField(max_length=20)),
                ('classes', models.CharField(max_length=30, null=True)),
                ('relation', models.CharField(max_length=60, null=True)),
                ('comment', models.CharField(max_length=60, null=True)),
                ('context', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('noun_property',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.NounProperty')),
            ],
        ),
    ]
