# Generated by Django 3.0.dev20190531161155 on 2019-06-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nounproperty',
            name='id',
        ),
        migrations.AddField(
            model_name='nounproperty',
            name='noun_property_id',
            field=models.IntegerField(auto_created=True, default=3, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
